// 사용자에게 보이는 문장은 모두 여기서만 꺼낸다. [자리] 표시는 확정 전 임시 문구.
export const copy = {
  'otp.sms': '[인싸이트] 서랍 인증번호 {code} (3분 안에 입력해 주세요)',
  'entry.title': '{name}님의 서랍이에요',
  'entry.send': '{phone}로 인증번호를 보낼게요',
  'entry.button': '인증번호 받기',
  'entry.notice': '[자리] 서랍 이용을 위해 개인정보를 처리해요. 자세한 내용은 개인정보 처리방침에서 볼 수 있어요',
  'otp.title': '인증번호를 입력해 주세요',
  'otp.remaining': '남은 시간 {time}',
  'otp.submit': '확인',
  'otp.resend': '새 번호 받기',
  'otp.noSms': '문자가 안 와요',
  'otp.noSms.help': '스팸 문자함을 확인해 주세요. 1분 뒤에 새 번호를 받을 수 있어요',
  'otp.wrong': '번호가 맞지 않아요. {n}번 더 틀리면 잠시 잠겨요',
  'otp.expired': '시간이 지났어요. 새 번호를 받아 주세요',
  'otp.locked': '여러 번 틀려서 잠겼어요. {time}에 다시 시도하거나 문의해 주세요',
  'otp.rateLimited': '잠시 후 다시 시도해 주세요. {time}부터 받을 수 있어요',
  'box.title': '{name}님의 서랍',
  'box.summary': '실시 전 {n}매',
  'box.tab.mine': '내 검사',
  'box.tab.history': '전달 이력',
  'box.group': '{date} 구매 · {product} · {n}매로 나눠 보여 드려요',
  'box.groupSingle': '{date} 구매 · {product}',
  'box.empty': '최근 12개월 동안 구매한 검사가 없어요',
  'box.logout': '로그아웃',
  'line.unit': '{n}매 중 {k}번째',
  'line.cancelled': '취소됨',
  'line.cancelChecking': '취소 확인 중',
  'line.preparing': '준비 중',
  'line.unusable': '사용할 수 없는 검사예요',
  'line.counselLocked': '신청서 제출 후 열려요',
  'line.checking': '확인 중',
  'line.completed': '완료',
  'line.inProgress': '응시 중',
  'line.unused': '미사용',
  'line.launched': '실시함 ({date})',
  'line.forwarded': '전달함 · {name}',
  'line.forwardOpened': '받는 분이 열어 봄',
  'line.forwardNotOpened': '아직 안 열어 봄',
  'line.notStarted': '실시 전',
  'line.cancelRejected': '취소할 수 없어요: {reason}',
  'action.launch': '실시하기',
  'action.continue': '이어서 하기',
  'action.forward': '전달하기',
  'action.resend': '다시 보내기',
  'action.reforward': '다른 분께',
  'action.contact': '문의하기',
  'action.counsel_form': '신청서 쓰기',
  'action.result_help': '결과 보는 법',
  'action.code': '코드 보기',
  'launch.choose': '이어서 할까요, 새 1매를 쓸까요?',
  'launch.continue': '이어서 하기',
  'launch.new': '새 1매 쓰기',
  'code.title': '검사 코드',
  'code.pcNote': 'PC에서는 인싸이트 사이트에서 코드를 입력해 주세요',
  'common.close': '닫기',
  'common.cancel': '취소',
  'common.confirm': '확인',
  'forward.title': '{test} 전달하기',
  'forward.name': '이름 또는 호칭',
  'forward.phone': '휴대폰 번호',
  'forward.child': '만 14세 미만이면 보호자 번호로 보내 주세요',
  'forward.night': '지금 보내면 밤에 알림이 갈 수 있어요',
  'forward.next': '다음',
  'forward.confirm': '이 번호가 맞나요?',
  'forward.send': '보내기',
  'forward.edit': '고치기',
  'forward.self': '본인 번호예요. 직접 실시하시겠어요?',
  'forward.selfSend': '그래도 보내기',
  'forward.more': '더보기',
  'forward.direct': '번호 없이 링크 복사하기',
  'forward.direct.warn': '직접 공유하면 받는 분이 기록되지 않아요',
  'forward.direct.copied': '링크를 복사했어요. 원하는 곳에 붙여넣어 주세요',
  'forward.direct.text': '[인싸이트 서랍] {sender}님이 심리검사를 보냈어요. {url}',
  'forward.sent': '{name}님께 보냈어요',
  'forward.resend.confirm': '{name}님께 다시 보낼까요?',
  'forward.reforward.confirm': '{name}님께 보낸 링크는 더 이상 열리지 않아요. 다른 분께 보낼까요?',
  'forward.exposed': '받는 분이 이미 코드를 확인해서 바꿀 수 없어요. 문의해 주세요',
  'forward.invalidName': '이름 또는 호칭을 1~20자로 입력해 주세요',
  'forward.invalidPhone': '휴대폰 번호를 확인해 주세요 (예: 010-1234-5678)',
  'limit.per_voucher_day': '이 검사는 오늘 더 보낼 수 없어요. {time}부터 다시 보낼 수 있어요',
  'limit.same_number_gap': '같은 번호로는 {time}부터 다시 보낼 수 있어요',
  'limit.per_box_day': '오늘은 더 보낼 수 없어요. {time}부터 다시 보낼 수 있어요',
  'history.line': '{name} / {phone} 님께 {at} 검사링크 전달 · {result}',
  'history.direct': '{at} 링크 직접 공유 · 받는 분 미확인',
  'history.cancel': '{at} {name}님께 보낸 전달을 취소함',
  'history.resendMark': '다시 보내기',
  'history.result.delivered_alimtalk': '알림톡 전달 완료',
  'history.result.delivered_sms': '문자로 전달 완료',
  'history.result.sending': '보내는 중',
  'history.result.failed': '전달 실패',
  'history.opened': '받는 분이 열어 봄',
  'history.empty': '아직 전달한 검사가 없어요',
  'state.linkInvalid': '링크가 맞지 않아요. 받은 알림톡의 링크를 다시 눌러 주세요',
  'state.linkRevoked': '이 링크는 더 이상 열 수 없어요. 보낸 분께 다시 요청해 주세요',
  'state.sessionExpired': '다시 인증해 주세요. 받은 알림톡의 링크를 다시 눌러 주세요',
  'state.notFound': '찾는 화면이 없어요',
  'state.blocked': '확인이 필요한 서랍이에요. 문의해 주세요',
  'maintenance': '확인 후 순서대로 보내 드려요. 급하시면 톡톡으로 문의해 주세요',
  'error.generic': '잠시 문제가 생겼어요. 잠시 후 다시 시도해 주세요',
  'placeholder.preparing': '서비스를 준비하고 있어요.',
  'brand.parent': '인싸이트',
  'brand.name': '서랍',
} as const

export type CopyKey = keyof typeof copy

export function t(key: CopyKey, vars: Record<string, string | number> = {}): string {
  return copy[key].replace(/\{(\w+)\}/g, (whole, name: string) =>
    Object.prototype.hasOwnProperty.call(vars, name) ? String(vars[name]) : whole,
  )
}
